Particular/NServiceBus.Persistence.ServiceFabric

src/NServiceBus.Persistence.ServiceFabric.Tests/NServiceBus.Persistence.ServiceFabric.Tests.csproj
src/NServiceBus.Persistence.ServiceFabric.Tests/Properties/AssemblyInfo.cs
src/NServiceBus.Persistence.ServiceFabric.Tests/packages.config
src/NServiceBus.Persistence.ServiceFabric.sln
src/NServiceBus.Persistence.ServiceFabric/NServiceBus.Persistence.ServiceFabric.csproj
src/NServiceBus.Persistence.ServiceFabric/Properties/AssemblyInfo.cs
src/NServiceBus.Persistence.ServiceFabric/packages.config

Initial structure with two projects

---

src/NServiceBus.Persistence.ServiceFabric.Tests/PersistenceTestsConfiguration.cs
src/NServiceBus.Persistence.ServiceFabric.Tests/SynchronizedStorage/StorageSessionTests.cs
src/NServiceBus.Persistence.ServiceFabric/Outbox/ServiceFabricOutboxPersistence.cs
src/NServiceBus.Persistence.ServiceFabric/Outbox/ServiceFabricOutboxStorage.cs
src/NServiceBus.Persistence.ServiceFabric/Outbox/ServiceFabricOutboxTransaction.cs
src/NServiceBus.Persistence.ServiceFabric/SynchronizedStorage/StorageSession.cs
src/NServiceBus.Persistence.ServiceFabric/SynchronizedStorage/SynchronizedStorage.cs
src/NServiceBus.Persistence.ServiceFabric/SynchronizedStorage/SynchronizedStorageAdapter.cs

Suggested changes to integrate the outbox tx & storage session

integrate outbox transaction & storage session

---

src/NServiceBus.Persistence.ServiceFabric.Tests/ComponentTests/PersistenceTestsConfiguration.cs
src/NServiceBus.Persistence.ServiceFabric.Tests/ComponentTests/Sagas/SagaPersisterTests.cs
src/NServiceBus.Persistence.ServiceFabric.Tests/PersistenceTestsConfiguration.cs
src/NServiceBus.Persistence.ServiceFabric/NServiceBus.Persistence.ServiceFabric.csproj
src/NServiceBus.Persistence.ServiceFabric/Sagas/SagaIdGenerator.cs
src/NServiceBus.Persistence.ServiceFabric/Sagas/SagaInfoCache.cs
src/NServiceBus.Persistence.ServiceFabric/Sagas/SagaPersistenceFeature.cs
src/NServiceBus.Persistence.ServiceFabric/Sagas/SagaPersister.cs

Replace ActiveSagaInstance usage with SagaMetadataCollection

---

packaging/nuget/nservicebus.persistence.servicefabric.nuspec
src/NServiceBus.Persistence.ServiceFabric.AcceptanceTests/NServiceBus.Persistence.ServiceFabric.AcceptanceTests.csproj
src/NServiceBus.Persistence.ServiceFabric.AcceptanceTests/packages.config
src/NServiceBus.Persistence.ServiceFabric.Tests/NServiceBus.Persistence.ServiceFabric.Tests.csproj
src/NServiceBus.Persistence.ServiceFabric.Tests/packages.config
src/NServiceBus.Persistence.ServiceFabric/NServiceBus.Persistence.ServiceFabric.csproj
src/NServiceBus.Persistence.ServiceFabric/packages.config
src/Tests/Tests.csproj
src/Tests/packages.config

Pulls in partial changes from #23 until flakiness can be addressed

Update to stable core 6.2

---

src/NServiceBus.Persistence.ServiceFabric.AcceptanceTests/AcceptanceTests.csproj
src/NServiceBus.Persistence.ServiceFabric.AcceptanceTestsApplication/AcceptanceTestsApplication.sfproj
src/NServiceBus.Persistence.ServiceFabric.AcceptanceTestsApplication/packages.config
src/NServiceBus.Persistence.ServiceFabric.Tests/NServiceBus.Persistence.ServiceFabric.Tests.csproj
src/NServiceBus.Persistence.ServiceFabric.TestsApplication/TestsApplication.sfproj
src/NServiceBus.Persistence.ServiceFabric.TestsApplication/packages.config
src/NServiceBus.Persistence.ServiceFabric/NServiceBus.Persistence.ServiceFabric.csproj
src/NServiceBus.Persistence.TestRunner/NServiceBus.Persistence.TestRunner.csproj
src/Tests/Tests.csproj

Update SF lib dependencies to 2.7.198 and 5.7.198

---

src/NServiceBus.Persistence.ServiceFabric.Tests/ComponentTests/Sagas/SagaPersisterTests.cs
src/NServiceBus.Persistence.ServiceFabric/Sagas/SagaPersister.cs

pending https://github.com/Particular/NServiceBus/pull/4923

Add saga class constraint

---

src/AcceptanceTestsApplication/AcceptanceTestsApplication.sfproj
src/AcceptanceTestsApplication/packages.config
src/ServiceFabricPersistence/ServiceFabricPersistence.csproj
src/TestRunner/TestRunner.csproj
src/TestsApplication/TestsApplication.sfproj
src/TestsApplication/packages.config

- Updated project to use the latest SF SDK 3.0
- Addressed nuget/cli tooling version issue from a previous PR (/cc @danielmarbach)

ServiceFabric SDK 3.0 update

---

src/NServiceBus.Persistence.ServiceFabric.AcceptanceTestsApplication/AcceptanceTestsApplication.sfproj
src/NServiceBus.Persistence.ServiceFabric.AcceptanceTestsApplication/packages.config
src/NServiceBus.Persistence.ServiceFabric.Tests/ComponentTests/OutboxStorageTests.cs
src/NServiceBus.Persistence.ServiceFabric.Tests/OutboxStorageServiceFabricSpecificTests.cs
src/NServiceBus.Persistence.ServiceFabric.TestsApplication/TestsApplication.sfproj
src/NServiceBus.Persistence.ServiceFabric.TestsApplication/packages.config
src/NServiceBus.Persistence.ServiceFabric/Outbox/OutboxStorage.cs

Hotfix 1.0.1

---

packaging/nuget/nservicebus.persistence.servicefabric.nuspec

Fix nuspec minimum ranges for Newtonsoft.Json and Microsoft.ServiceFabric.Data

Fix minimum nuget version range

---

src/ApiTests/ApiTests.csproj
src/ServiceFabricPersistence/ServiceFabricPersistence.csproj
src/TestRunner/CompositeListener.cs
src/TestRunner/EventSourceTestListener.cs
src/TestRunner/ResultListener.cs
src/TestRunner/StatefulServiceProviderListener.cs
src/TestRunner/TestRunner.csproj

updating newtonsoft.json package

---

src/ApiTests/ApiTests.csproj
src/TestHarness/TestHarness.csproj

This updates development tooling on the `develop` branch.
Note: This should not be squashed.

develop-update dev tooling

---

src/ApiTests/ApiTests.csproj
src/TestHarness/TestHarness.csproj

This updates development tooling on the `master` branch.
Note: This should not be squashed.

master-update testing packages

---

src/ApiTests/ApiApproval.cs
src/ApiTests/ApiTests.csproj
src/ApiTests/ApprovalFiles/APIApprovals.ApproveServiceFabricPersistence.approved.txt
src/ServiceFabricPersistence/ServiceFabricPersistence.csproj
src/TestHarness/TestHarness.csproj
src/TestRunner/CompositeListener.cs
src/TestRunner/EventSourceTestListener.cs
src/TestRunner/FullNameFilter.cs
src/TestRunner/ResultListener.cs
src/TestRunner/StatefulServiceProviderListener.cs
src/TestRunner/TestRunner.csproj

This updates development tooling on the `support-2.0` branch.
Note: It is okay for this to be squashed.

Update development tooling

---

src/NServiceBus.Persistence.ServiceFabric.AcceptanceTests/AcceptanceTests.csproj
src/NServiceBus.Persistence.ServiceFabric.Tests/NServiceBus.Persistence.ServiceFabric.Tests.csproj
src/NServiceBus.Persistence.ServiceFabric/NServiceBus.Persistence.ServiceFabric.csproj
src/NServiceBus.Persistence.TestRunner/CommunicationListener.cs
src/NServiceBus.Persistence.TestRunner/CompositeListener.cs
src/NServiceBus.Persistence.TestRunner/EventSourceTestListener.cs
src/NServiceBus.Persistence.TestRunner/FullNameFilter.cs
src/NServiceBus.Persistence.TestRunner/NServiceBus.Persistence.TestRunner.csproj
src/NServiceBus.Persistence.TestRunner/ResultListener.cs
src/NServiceBus.Persistence.TestRunner/StatefulServiceProviderListener.cs
src/Tests/ApiApproval.cs
src/Tests/ApprovalFiles/ApiApproval.Approve.approved.txt
src/Tests/ApprovalTestConfig.cs
src/Tests/Tests.csproj

This updates development tooling on the `support-1.1.1` branch.
Note: This should not be squashed.

Support-1.1 update dev tooling

---

src/ServiceFabricPersistence/ServiceFabricPersistenceStorageSessionExtensions.cs

Closes https://github.com/Particular/NServiceBus.Persistence.ServiceFabric/issues/94

Use IServiceFabricStorageSession instead of internal type

---

src/AcceptanceTests/AcceptanceTests.csproj
src/ApiTests/ApiTests.csproj
src/TestRunner/TestRunner.csproj
src/Tests/Tests.csproj

Update NServiceBus Core to 7.2

---

GitVersion.yml
src/ServiceFabricPersistence/ServiceFabricPersistence.csproj

Update Particular.Packaging in master

---

GitVersion.yml
src/ServiceFabricPersistence/ServiceFabricPersistence.csproj

Update Particular.Packaging in release-2.1

---

src/AcceptanceTests/AcceptanceTests.csproj
src/AcceptanceTests/ConfigureEndpointAzureServiceBusTransport.cs

Switch to Azure Service Bus Netstandard

---

.gitignore
src/.gitignore

Fixes https://github.com/Particular/NServiceBus.Persistence.ServiceFabric/pull/126

Moved custom exclusions to src folder

---

src/ApiTests/ApprovalFiles/APIApprovals.ApproveServiceFabricPersistence.approved.txt
src/ServiceFabricPersistence/Testing/TestableServiceFabricStorageSession.cs
src/Tests/Testing/TestableStorageSessionTests.cs
src/Tests/Tests.csproj

Introduces a testable storage session

Introduce a testable storage session

---

src/ApiTests/ApiApproval.cs

This was missed out in the previous round of work.

Complete fix for API Approvals - release 2.4

---

src/ServiceFabricPersistence/ServiceFabricPersistence.csproj
src/TestRunner/TestRunner.csproj

Target framework update to netcoreapp2.1 as part of https://github.com/Particular/Exploration/issues/482

upgrade target framework

---

src/ServiceFabricPersistence/ServiceFabricPersistence.csproj
src/TestRunner/TestRunner.csproj

Updating ServiceFabric to version 5, it can be incorporated with next major

Updating ServiceFabric to version 5

---

src/ServiceFabricPersistence/ServiceFabricPersistence.csproj
src/TestRunner/TestRunner.csproj

Related to https://github.com/Particular/NServiceBus.Persistence.ServiceFabric/issues/336

Support for Microsoft.ServiceFabric.Data 6.x

---

.github/workflows/ci.yml
.github/workflows/release.yml
src/AcceptanceTests/AcceptanceTests.csproj
src/PersistenceTests/PersistenceTests.csproj
src/Tests/Tests.csproj

Update workflow files

---

src/PersistenceTests/PersistenceTests.csproj

Adding dependencies to the Test project so Dependabot will keep track of them and notify use of issues

Add ranged version dependencies to test project

---

.github/workflows/ci.yml
.github/workflows/release.yml

- update workflow
- update workflows'

update workflows 2.6
